# Generated by Django 2.2.1 on 2019-05-24 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='modelo',
        ),
        migrations.AddField(
            model_name='modelo',
            name='sizes',
            field=models.ManyToManyField(to='store.Size'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='typeProduct',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.Type'),
        ),
    ]
