# Generated by Django 2.2.1 on 2019-05-27 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20190526_2248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['published_date']},
        ),
    ]
